### ISSUE TITLE
Multiple errors+bugs.

### ISSUE THREAD

**Issue by Weeeishy** [shanapu/MyJailbreak#2]
1- DuckHunt day is not working.

```
L 05/10/2016 - 01:31:19: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 05/10/2016 - 01:31:19: [SM] Native "VFormat" reported: Language phrase "duckhunt_tag" not found
L 05/10/2016 - 01:31:19: [SM] Displaying call stack trace for plugin "MyJailbreak\duckhunt.smx":
L 05/10/2016 - 01:31:19: [SM]   [0]  Line 174, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\colors.inc::CPrintToChatAll()
L 05/10/2016 - 01:31:19: [SM]   [1]  Line 291, MyJailbreak/duckhunt.sp::StartNextRound()
L 05/10/2016 - 01:31:19: [SM]   [2]  Line 213, MyJailbreak/duckhunt.sp::SetDuckHunt()
```

These errors are also showing up on my errors log.

```
L 05/10/2016 - 01:14:39: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 05/10/2016 - 01:14:39: [SM] Native "VFormat" reported: Language phrase "jihad_needc4" not found
L 05/10/2016 - 01:14:39: [SM] Displaying call stack trace for plugin "MyJailbreak\Jihad.smx":
L 05/10/2016 - 01:14:39: [SM]   [0]  Line 78, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\colors.inc::CPrintToChat()
L 05/10/2016 - 01:14:39: [SM]   [1]  Line 620, MyJailbreak/jihad.sp::Command_BombJihad()
L 05/10/2016 - 01:14:39: [SM]   [2]  Line 539, MyJailbreak/jihad.sp::Command_LAW()
```

```
L 05/10/2016 - 00:55:33: [SM] Plugin encountered error 15: Array index is out of bounds
L 05/10/2016 - 00:55:33: [SM] Displaying call stack trace for plugin "MyJailbreak\warden.smx":
L 05/10/2016 - 00:55:33: [SM]   [0]  Line 1295, MyJailbreak/warden.sp::RemoveMarker()
L 05/10/2016 - 00:55:33: [SM]   [1]  Line 1192, MyJailbreak/warden.sp::MarkerMenu()
L 05/10/2016 - 00:55:33: [SM]   [2]  Line 1166, MyJailbreak/warden.sp::OnPlayerRunCmd()
```

**Comment by shanapu** [comment]
```
L 05/10/2016 - 01:31:19: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 05/10/2016 - 01:31:19: [SM] Native "VFormat" reported: Language phrase "duckhunt_tag" not found
L 05/10/2016 - 01:31:19: [SM] Displaying call stack trace for plugin "MyJailbreak\duckhunt.smx":
L 05/10/2016 - 01:31:19: [SM]   [0]  Line 174, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\colors.inc::CPrintToChatAll()
L 05/10/2016 - 01:31:19: [SM]   [1]  Line 291, MyJailbreak/duckhunt.sp::StartNextRound()
L 05/10/2016 - 01:31:19: [SM]   [2]  Line 213, MyJailbreak/duckhunt.sp::SetDuckHunt()
```
[fixed](https://github.com/shanapu/MyJailbreak/commit/8d52b120cadc98926588405043f4334c8dc9be51#diff-9bccc2216130f73a430ff40f4964ff59) 

```
L 05/10/2016 - 01:14:39: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 05/10/2016 - 01:14:39: [SM] Native "VFormat" reported: Language phrase "jihad_needc4" not found
L 05/10/2016 - 01:14:39: [SM] Displaying call stack trace for plugin "MyJailbreak\Jihad.smx":
L 05/10/2016 - 01:14:39: [SM]   [0]  Line 78, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\colors.inc::CPrintToChat()
L 05/10/2016 - 01:14:39: [SM]   [1]  Line 620, MyJailbreak/jihad.sp::Command_BombJihad()
L 05/10/2016 - 01:14:39: [SM]   [2]  Line 539, MyJailbreak/jihad.sp::Command_LAW()
```
[fixed](https://github.com/shanapu/MyJailbreak/commit/03a8d5fc8fe47eebd9547b7e374fa595ed6134b4#diff-71a2bc177df915a1aead6a3c4da5808aL620)

```
L 05/10/2016 - 00:55:33: [SM] Plugin encountered error 15: Array index is out of bounds
L 05/10/2016 - 00:55:33: [SM] Displaying call stack trace for plugin "MyJailbreak\warden.smx":
L 05/10/2016 - 00:55:33: [SM]   [0]  Line 1295, MyJailbreak/warden.sp::RemoveMarker()
L 05/10/2016 - 00:55:33: [SM]   [1]  Line 1192, MyJailbreak/warden.sp::MarkerMenu()
L 05/10/2016 - 00:55:33: [SM]   [2]  Line 1166, MyJailbreak/warden.sp::OnPlayerRunCmd()
```
[fixed]
(https://github.com/shanapu/MyJailbreak/commit/476b85610325a7f3f1da3fd82ce6a28808119a2c#diff-85431a27e7ef4b9224d788cde2e14fbaL1118)

**Comment by shanapu** [comment]
Thanks! for reporting!

**Comment by Weeeishy** [comment]
Sorry for reopening the issue. This error is still spamming the error logs.

`L 05/10/2016 - 23:14:11: [SM] Plugin encountered error 15: Array index is out of bounds
L 05/10/2016 - 23:14:11: [SM] Displaying call stack trace for plugin "MyJailbreak\warden.smx":
L 05/10/2016 - 23:14:11: [SM]   [0]  Line 1300, MyJailbreak/warden.sp::RemoveMarker()
L 05/10/2016 - 23:14:11: [SM]   [1]  Line 1189, MyJailbreak/warden.sp::MarkerMenu()
L 05/10/2016 - 23:14:11: [SM]   [2]  Line 1369, MyJailbreak/warden.sp::OnPlayerRunCmd()`

Thanks!

**Comment by Weeeishy** [comment]
Hi again,

The colors on the lasers are not working, its only showing the mix.

https://i.gyazo.com/9be66437d99a8fbc34ad12c950740b81.jpg  I chose the blue laser here.


Also I've noticed another error showing up.

`L 05/11/2016 - 07:58:01: [SM] Native "PrintHintText" reported: Client 2 is not in game
L 05/11/2016 - 07:58:01: [SM] Displaying call stack trace for plugin "MyJailbreak\freeday.smx":
L 05/11/2016 - 07:58:01: [SM]   [0]  Line 290, MyJailbreak/freeday.sp::RoundStart()`

**Comment by shanapu** [comment]
> The colors on the lasers are not working, its only showing the mix.

On your screencap the LaserPointer is Blue. Only the Drawer is Rainbow.

**Laser Pointer   !=   Drawer**     both are different features with different settings. 
Take a look to menu. There is a "Laser Pointer Menu" & "Drawer Menu" - or !laser & !drawer

```
L 05/11/2016 - 07:58:01: [SM] Native "PrintHintText" reported: Client 2 is not in game
L 05/11/2016 - 07:58:01: [SM] Displaying call stack trace for plugin "MyJailbreak\freeday.smx":
L 05/11/2016 - 07:58:01: [SM]   [0]  Line 290, MyJailbreak/freeday.sp::RoundStart()
```
forgot to check if player is alive.

```
L 05/10/2016 - 23:14:11: [SM] Plugin encountered error 15: Array index is out of bounds
L 05/10/2016 - 23:14:11: [SM] Displaying call stack trace for plugin "MyJailbreak\warden.smx":
L 05/10/2016 - 23:14:11: [SM]   [0]  Line 1300, MyJailbreak/warden.sp::RemoveMarker()
L 05/10/2016 - 23:14:11: [SM]   [1]  Line 1189, MyJailbreak/warden.sp::MarkerMenu()
L 05/10/2016 - 23:14:11: [SM]   [2]  Line 1369, MyJailbreak/warden.sp::OnPlayerRunCmd()
```
should be fixxed now, but needs further testing.
  
  
btw. Is "Drawer" a good name for this feature? Or maybe better "Painter" or "LazZzer Paint" or something else? Im bad in naming.

**Comment by Weeeishy** [comment]
Thanks. 

The names are fine haha.

so Im getting this error with the updated smx.

```
L 05/12/2016 - 03:02:56: [SM] Native "KillTimer" reported: Invalid timer handle ba7e0b00 (error 1)
L 05/12/2016 - 03:02:56: [SM] Displaying call stack trace for plugin "MyJailbreak\noscope.smx":
L 05/12/2016 - 03:02:56: [SM]   [0]  Line 510, MyJailbreak/noscope.sp::OnMapEnd()
```

**Comment by shanapu** [comment]
Should be fixed now.

https://github.com/shanapu/MyJailbreak/commit/670ff141be1f6f531bcad8e6e3487087a1989944

**Comment by Weeeishy** [comment]
Saw that error so I wanted to throw it here


```
L 05/13/2016 - 11:43:32: [SM] Native "GetClientTeam" reported: Client 3 is not in game
L 05/13/2016 - 11:43:32: [SM] Displaying call stack trace for plugin "MyJailbreak\warden.smx":
L 05/13/2016 - 11:43:32: [SM]   [0]  Line 1791, MyJailbreak/warden.sp::ToggleDrawerT()
L 05/13/2016 - 11:43:32: [SM]   [1]  Line 1640, MyJailbreak/warden.sp::DrawerHandler()
```

**Comment by shanapu** [comment]
annnnnnnnnd it's fixed. https://github.com/shanapu/MyJailbreak/commit/a7fd95823f48ea278efb184233ddb5f34445075d

**Comment by Weeeishy** [comment]
Hello,

New error

`L 05/15/2016 - 04:30:43: [SM] Unable to load plugin "MyJailbreak\zombie.smx": Could not find required plugin "CustomPlayerSkins"`

**Comment by Weeeishy** [comment]
Found this before the update you've just posted 2/3 hours ago.

```
L 05/15/2016 - 07:36:31: [SM] Plugin encountered error 15: Array index is out of bounds
L 05/15/2016 - 07:36:31: [SM] Displaying call stack trace for plugin "MyJailbreak\request.smx":
L 05/15/2016 - 07:36:31: [SM]   [0]  Line 557, MyJailbreak/request.sp::OnTakedamage()
```

**Comment by Weeeishy** [comment]
Another error after updating to the last commit.

```
L 05/15/2016 - 11:02:49: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 05/15/2016 - 11:02:49: [SM] Native "Format" reported: Language phrase "warden_cdmenu_Title2" not found
L 05/15/2016 - 11:02:49: [SM] Displaying call stack trace for plugin "MyJailbreak\warden.smx":
L 05/15/2016 - 11:02:49: [SM]   [0]  Line 2106, MyJailbreak/warden.sp::StartStopCDMenu()
```

**Comment by shanapu** [comment]
fixed the typos.
fixed the mission "warden_cdmenu_Title2".
fixed error in MyJailbreak\request.smx.

> Also what if a guard swaps a gun instead of dropping it won't get him damaged? Because most likely its a legit move instead of gun planting.
You can disable slap & damage with
```
- sm_warden_gunslap: 0 - disabled, 1 - Slap the CT for dropping a gun. Default 1
- sm_warden_gunslap_dmg: Amoung of HP losing on slap for dropping a gun. Default 10
```
i think i will insert a timer-convar. Time after roundstart you allowed to drop/change weapon.

**Comment by Weeeishy** [comment]
Thanks!

A new error showing up

```
L 05/16/2016 - 13:49:04: [SM] Native "GetEntPropEnt" reported: Entity 77 (77) is invalid
L 05/16/2016 - 13:49:04: [SM] Displaying call stack trace for plugin "MyJailbreak\warden.smx":
L 05/16/2016 - 13:49:04: [SM]   [0]  Line 30, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\smlib/weapons.inc::Weapon_GetOwner()
L 05/16/2016 - 13:49:04: [SM]   [1]  Line 2770, MyJailbreak/warden.sp::DroppedWeapon()
```

**Comment by Weeeishy** [comment]
Another error

```
L 05/16/2016 - 15:49:43: [SM] Plugin encountered error 22: Maximum number of parameters reached
L 05/16/2016 - 15:49:43: [SM] Native "VFormat" reported: Translation string formatted incorrectly - missing at least 1 parameters
L 05/16/2016 - 15:49:43: [SM] Displaying call stack trace for plugin "MyJailbreak\warden.smx":
L 05/16/2016 - 15:49:43: [SM]   [0]  Line 174, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\colors.inc::CPrintToChatAll()
L 05/16/2016 - 15:49:43: [SM]   [1]  Line 939, MyJailbreak/warden.sp::EventPlayerTeam()
```

```
L 05/16/2016 - 15:58:57: [SM] Native "IsPlayerAlive" reported: Client 7 is not in game
L 05/16/2016 - 15:58:57: [SM] Displaying call stack trace for plugin "MyJailbreak\warden.smx":
L 05/16/2016 - 15:58:57: [SM]   [0]  Line 2562, MyJailbreak/warden.sp::GetAlivePlayersCount()
L 05/16/2016 - 15:58:57: [SM]   [1]  Line 2523, MyJailbreak/warden.sp::killmenu()
```

```
L 05/16/2016 - 22:16:50: [SM] Native "SetEntProp" reported: Entity -1 (-1) is invalid
L 05/16/2016 - 22:16:50: [SM] Displaying call stack trace for plugin "MyJailbreak\zombie.smx":
L 05/16/2016 - 22:16:50: [SM]   [0]  Line 519, MyJailbreak/zombie.sp::Glow_Timer()
```

```
L 05/16/2016 - 22:21:53: [SM] Native "GetClientModel" reported: Client 11 is not in game
L 05/16/2016 - 22:21:53: [SM] Displaying call stack trace for plugin "MyJailbreak\zombie.smx":
L 05/16/2016 - 22:21:53: [SM]   [0]  Line 517, MyJailbreak/zombie.sp::Glow_Timer()
L 05/16/2016 - 22:21:54: [SM] Native "GetClientModel" reported: Client 1 is not in game
```

**Comment by shanapu** [comment]
thanks for reporting and sorry for all this new errors....
BUT i should fixed them!

**Comment by Weeeishy** [comment]
No problem. I see that you've added !guard, is there any way to disable it? Because I have that command for my ratio balance plugin.

**Comment by shanapu** [comment]
>  I see that you've added !guard, is there any way to disable it? Because I have that command for my ratio balance plugin.

the menu plugin check if there is a command !guard (sm_guard). 
If yes the menu shows you !guard option. 
If there is no command like !guard the menu show you the default JoinCT.

i haven't insert a !guard command or ratio (,yet).  Should work with "Jailbreak Team Balance" and other ratio plugins outthere, that using sm_guard

**Comment by Weeeishy** [comment]
Ahh I see.

That's the only error I've seen lately.

```
L 05/17/2016 - 16:11:28: [SM] Native "GetEntPropEnt" reported: Entity 1290 (1290) is invalid
L 05/17/2016 - 16:11:28: [SM] Displaying call stack trace for plugin "MyJailbreak\warden.smx":
L 05/17/2016 - 16:11:28: [SM]   [0]  Line 30, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\smlib/weapons.inc::Weapon_GetOwner()
L 05/17/2016 - 16:11:28: [SM]   [1]  Line 2858, MyJailbreak/warden.sp::DroppedWeapon()
```

**Comment by Weeeishy** [comment]
List of updated errors as of today.

```
L 05/18/2016 - 20:18:37: [SM] Native "GetEntPropEnt" reported: Entity 223 (223) is invalid
L 05/18/2016 - 20:18:37: [SM] Displaying call stack trace for plugin "MyJailbreak\warden.smx":
L 05/18/2016 - 20:18:37: [SM]   [0]  Line 30, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\smlib/weapons.inc::Weapon_GetOwner()
L 05/18/2016 - 20:18:37: [SM]   [1]  Line 2783, MyJailbreak/warden.sp::DroppedWeapon()
```

```
L 05/18/2016 - 16:29:10: [SM] Native "GetEntPropEnt" reported: Property "m_hOwner" not found (entity 116/func_button)
L 05/18/2016 - 16:29:10: [SM] Displaying call stack trace for plugin "MyJailbreak\warden.smx":
L 05/18/2016 - 16:29:10: [SM]   [0]  Line 30, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\smlib/weapons.inc::Weapon_GetOwner()
L 05/18/2016 - 16:29:10: [SM]   [1]  Line 2806, MyJailbreak/warden.sp::RemoveWeapon()
```

**Comment by Weeeishy** [comment]
Hi,

I have a question and a suggestion

1- Suggestion: By default my server is on casual mode, so noblock is always on. switching it off or on does nothing for me. It would be awesome to make the block on as a feature for the warden.

2- I have this cvar on my server enabled "mp_drop_knife_enable". I've noticed recently that players can't pickup their knifes after dropping it. I think something from your mod preventing that? Because I haven't added any plugins recently to my server other than updating yours.


Thanks

**Comment by bchewy** [comment]
@Weeeishy If you're using a store plugin and players have dropped their spawned knifes (meaning that the knife is a duplicate knife or a "fake" knife ) they won't be able to pick them up because its given to them by the server.

I'd suggest adding a custom feature called "weapon" which i can come up with in a little and submit a pull request :D 

so 
- sm_weapon <weapon name> will spawn the weapon/knife
- sm_sk - spawns a knife?

Something like that, we'll see. but that's something you can't really use unless the player's knife is a real one they own.

Feel free to contact me on steam here : http://steamcommunity.com//id/anony32

**Comment by shanapu** [comment]
> 1- Suggestion: By default my server is on casual mode, so noblock is always on. switching it off or on does nothing for me. It would be awesome to make the block on as a feature for the warden.

originally No Block toggled just the collision of CT vs T player, not in a Team itself. but now I added `mp_solid_teammates` to the function. now it will be noblock for all. Beware, if 2 or more player standing inside on toggle they get stuck.

> 2- Question: I have this cvar on my server enabled "mp_drop_knife_enable". I've noticed recently that players can't pickup their knifes after dropping it. I think something from your mod preventing that? Because I haven't added any plugins recently to my server other than updating yours.

Standard knife droping and pick up works on my testserver ("only" sm_hosties & Myjailbreak). No restrictions. 

> If you're using a store plugin and players have dropped their spawned knifes (meaning that the knife is a duplicate knife or a "fake" knife ) they won't be able to pick them up because its given to them by the server.

**Comment by Weeeishy** [comment]
Thank you guys!

Another error found on my logs

```
L 05/19/2016 - 15:35:06: [SM] Native "SDKHooks_DropWeapon" reported: Weapon 76 is not owned by client 10
L 05/19/2016 - 15:35:06: [SM] Displaying call stack trace for plugin "MyJailbreak\myjailbreak.smx":
L 05/19/2016 - 15:35:06: [SM]   [0]  Line 75, D:\Code\MyJailbreak\addons\sourcemod\scripting\include\myjailbreak.inc::StripAllWeapons()
L 05/19/2016 - 15:35:06: [SM]   [1]  Line 76, MyJailbreak/myjailbreak.sp::RoundStart()
```

**Comment by shanapu** [comment]
removed obsolent code https://github.com/shanapu/MyJailbreak/commit/a86369c3c0c097c09053bf1d0c4275e5e856bd0d
