### ISSUE TITLE
Warden plugin keeps breaking

### ISSUE THREAD

**Issue by zeddy1234** [shanapu/MyJailbreak#288]
Hey, after a few maps, warden plugin just breaks.

In the centre / top hud, you can see Prisoners and Guards : , but there is no warden.

And !w or !warden shows as unknown command.

Has anyone had issues like this? The error logs shows nothing.

**Comment by shanapu** [comment]
Never heard of this problem before.
When this issue occurs and !w don't work. please type `sm plugins list` in your server console and reply the output.

**Comment by tistio1987** [comment]
me too ,,, 

i have some Error info 

sm version 
SourceMod Version Information:
    SourceMod Version: 1.8.0.6047
    SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.6047)
    SourcePawn API: v1 = 4, v2 = 11
    Compiled on: Jun  3 2018 09:55:59
    Built from: https://github.com/alliedmodders/sourcemod/commit/5e14ad86
    Build ID: 6047:5e14ad86
    http://www.sourcemod.net/

Meta Version
Metamod:Source version 1.10.7-dev
Built from: https://github.com/alliedmodders/metamod-source/commit/f255fa5
Build ID: 961:f255fa5
Loaded As: Valve Server Plugin
Compiled on: Nov  5 2017
Plugin interface version: 15:14
SourceHook version: 5:5
http://www.metamodsource.net/

meta list 
Listing 7 plugins:
  [01] SourceMod (1.8.0.6047) by AlliedModders LLC
  [02] CS Tools (1.8.0.6047) by AlliedModders LLC
  [03] SDK Tools (1.8.0.6047) by AlliedModders LLC
  [04] PTaH (P Tools and Hooks) (1.0.8) by Phoenix (????壬菩請覜碧????)
  [05] SDK Hooks (1.8.0.6047) by AlliedModders LLC
  [06] SteamWorks Extension (1.2.2) by Kyle Sanderson
  [07] DHooks (2.2.0) by Dr!fter

sm plugins list
[SM] Listing 73 plugins:
  01 "Admin File Reader" (1.8.0.6047) by AlliedModders LLC
  02 "Admin Help" (1.8.0.6047) by AlliedModders LLC
  03 "Admin Menu" (1.8.0.6047) by AlliedModders LLC
  04 "AFK Manager" (4.2.5) by Rothgar
  05 "Anti-Flood" (1.8.0.6047) by AlliedModders LLC
  06 "Basic Chat" (1.8.0.6047) by AlliedModders LLC
  07 "Basic Comm Control" (1.8.0.6047) by AlliedModders LLC
  08 "Basic Commands" (1.8.0.6047) by AlliedModders LLC
  09 "Basic Info Triggers" (1.8.0.6047) by AlliedModders LLC
  10 "Basic Votes" (1.8.0.6047) by AlliedModders LLC
  11 "blocksm\sbp.smx"
  12 "Connect Announce" (1.8) by Arg!
  13 "Chat-Processor" (2.1.4) by Keith Warren (Shaders Allen)
  14 "[Any] Chat Logging Redux + RTF Support" (1.1.2) by McFlurry, Keith Warren
(Shaders Allen)
  15 "Client Preferences" (1.8.0.6047) by AlliedModders LLC
  16 "Log Connections" (1.2a) by Xander and IT-KiLLER
  17 "Custom Player Skins (Core)" (1.4) by Mitchell, Root
  18 "Fun Commands" (1.8.0.6047) by AlliedModders LLC
  19 "Fun Votes" (1.8.0.6047) by AlliedModders LLC
  20 "Smart Jail Doors" (0.5.2-beta) by Maxim 'Kailo' Telezhenko
  21 "MyJailbreak - Arms Race" (Beta 13.0.dev-77015e8) by shanapu
  22 "MyJailbreak - Catch & Freeze" (Beta 13.0.dev-77015e8) by shanapu
  23 "MyJailbreak - CowBoy" (Beta 13.0.dev-77015e8) by shanapu
  24 "MyJailbreak - DealDamage" (Beta 13.0.dev-77015e8) by shanapu
  25 "MyJailbreak - Drunk" (Beta 13.0.dev-77015e8) by shanapu
  26 "MyJailbreak - DuckHunt" (Beta 13.0.dev-77015e8) by shanapu
  27 "MyJailbreak - War FFA" (Beta 13.0.dev-77015e8) by shanapu
  28 "MyJailbreak - Freeday" (Beta 13.0.dev-77015e8) by shanapu
  29 "MyJailbreak - Ghosts War" (Beta 13.0.dev-77015e8) by shanapu
  30 "MyJailbreak - HE Battle" (Beta 13.0.dev-77015e8) by shanapu
  31 "MyJailbreak - HideInTheDark" (Beta 13.0.dev-77015e8) by shanapu
  32 "MyJailbreak - Player HUD" (Beta 13.0.dev-77015e8) by shanapu
  33 "MyJailbreak - Icons" (Beta 13.0.dev-77015e8) by shanapu
  34 "MyJailbreak - KnifeFight" (Beta 13.0.dev-77015e8) by shanapu
  35 "MyJailbreak - Last Guard Rule" (Beta 13.0.dev-77015e8) by shanapu
  36 "MyJailbreak - Menus" (Beta 13.0.dev-77015e8) by shanapu
  37 "MyJailbreak - Core" (Beta 13.0.dev-77015e8) by shanapu
  38 "MyJailbreak - NoScope" (Beta 13.0.dev-77015e8) by shanapu
  39 "MyJailbreak - OneInTheChamber" (Beta 13.0.dev-77015e8) by Hexah | shanapu
  40 "MyJailbreak - Ratio" (Beta 13.0.dev-77015e8) by shanapu, Addicted
  41 "MyJailbreak - Request" (Beta 13.0.dev-77015e8) by shanapu
  42 "MyJailbreak - Suicide Bomber" (Beta 13.0.dev-77015e8) by shanapu
  43 "MyJailbreak - Teleport War" (Beta 13.0.dev-77015e8) by shanapu
  44 "MyJailbreak - Torch Relay" (Beta 13.0.dev-77015e8) by shanapu
  45 "MyJailbreak - War" (Beta 13.0.dev-77015e8) by shanapu
  46 "MyJailbreak - Weapons" (Beta 13.0.dev-77015e8) by shanapu
  47 "MyJailbreak - Zeus" (Beta 13.0.dev-77015e8) by shanapu
  48 "MyJailbreak - Zombie" (Beta 13.0.dev-77015e8) by shanapu
  49 "Nextmap" (1.8.0.6047) by AlliedModders LLC
  50 "Player Commands" (1.8.0.6047) by AlliedModders LLC
  51 "Reserved Slots" (1.8.0.6047) by AlliedModders LLC
  52 "ServerAdvertisements3" (3.1.3) by ESK0
  53 "SM_Hosties v2" (2.3.0) by databomb & dataviruset & comando
  54 "Advanced Parachute" (1.0) by ESK0
  55 "Sound Commands" (1.8.0.6047) by AlliedModders LLC
  56 "SourceBans++: Admin Config Loader" (1.6.3) by AlliedModders LLC, SourceBan
s++ Dev Team
  57 "SourceBans++: Bans Checker" (1.6.3) by psychonic, Ca$h Munny, SourceBans++
 Dev Team
  58 "SourceBans++: SourceComms" (1.6.3) by Alex, SourceBans++ Dev Team
  59 "SourceBans++ Discord Plugin" (1.0.4) by RumbleFrog, SourceBans++ Dev Team
  60 "SourceBans++: Main Plugin" (1.6.3) by SourceBans Development Team, SourceB
ans++ Dev Team
  61 "SourceBans++ Report Plugin" (1.6.3) by RumbleFrog, SourceBans++ Dev Team
  62 "SourceBans++: SourceSleuth" (1.6.3) by ecca, SourceBans++ Dev Team
  63 "[CSGO] Arms Fix" (1.5) by Kyle
  64 "Store - The Resurrection" (2.2.353) by Kyle
  65 "S-Downloader" (1.1.2.22 - Dev) by Starbish
  66 "VoiceAnnounceEx" (2.1.2) by Franc1sco franug, Mini and GoD-Tony
  67 "MapChooser Redux" (1.3beta6.123) by Kyle
  68 "Map Lister Redux" (1.3beta6.123) by Kyle
  69 "Map Time Extend Redux" (1.3beta6.123) by Kyle
  70 "Nominations Redux" (1.3beta6.123) by Kyle
  71 "Rock The Vote Redux" (1.3beta6.123) by Kyle
  72 "MyJailbreak - PlayerTags" (Beta 13.0.dev-77015e8) by shanapu
  73 <Error> "MyJailbreak - Warden" (Beta 13.0.dev-77015e8) by shanapu
Errors:
myjb\warden.smx (MyJailbreak - Warden): Error detected in plugin startup (see er
ror logs)

L 06/17/2018 - 20:14:00: Info (map "jail_west_v2") (file "errors_20180617.log")
L 06/17/2018 - 20:14:00: [SM] Exception reported: Property "m_iPrimaryReserveAmmoCount" not found (entity 90/weapon_taser)
L 06/17/2018 - 20:14:00: [SM] Blaming: myjb\warden.smx
L 06/17/2018 - 20:14:00: [SM] Call stack trace:
L 06/17/2018 - 20:14:00: [SM]   [0] SetEntProp
L 06/17/2018 - 20:14:00: [SM]   [1] Line 248, C:\Users\user\Desktop\scripting\include\mystocks.inc::SetPlayerAmmo
L 06/17/2018 - 20:14:00: [SM]   [2] Line 247, MyJailbreak/Modules/Warden/handcuffs.sp::HandCuffs_Event_WeaponFire
L 06/17/2018 - 20:16:04: Error log file session closed.

some time check Error log nothing

i test MyJB-dev-2730ab6,MyJB-dev-77015e8
and only Run sourceban + myJB still get the error

**Comment by shanapu** [comment]
Hi, thanks for report!
I can reproduce this error and will provide a fix soon.

**Comment by shanapu** [comment]
fixed.

**Comment by tistio1987** [comment]
@shanapu 
thank u FIx
but still have problem
test server only Run 
sourcemod:1.8.0.6047,
Metamod:Source:1.10.7
myjb(master 0465720 and 4882445) 
SM_Hosties 2.3

after a 20 up map warden breaks
server Console type sm plugins list get

Errors:
playertags.smx (MyJailbreak - PlayerTags): MyJailbreak PlayerTags - Can't open File: addons\sourcemod\configs\MyJailbreak\player_tags.cfg
warden.smx (MyJailbreak - Warden): MyJailbreak Warden - Can't open File: addons\
sourcemod\configs\MyJailbreak\orders.cfg

i change next map 

server Console type sm plugins list get

Errors:
warden.smx (MyJailbreak - Warden): Error detected in plugin startup (see error l
ogs)

but ... i check error log  shows nothing.
